---
version: "2.1"
services:
  auction-watcher-ebay:
    image: local/auctions-bot
    container_name: auctions-bot
    network_mode: host
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - 8888:8080
    environment:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: postgres
        CHROME_HOST: localhost
        CHROME_PORT: 4444
        TZ: Europe/Warsaw

